In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [11]:
## your code
a = np.ones(20)
s = np.arange(1,21,1)
((2*a)**s)/s

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [15]:
## your code
s = np.arange(0,5,1)
((0.1**(3*s))*(0.2**(4*s))).sum()

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [29]:
## your code
mat = np.zeros((8,8))
mat[1::2,::2] = 1
mat[::2,1::2] = 1
print(mat)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [34]:
X = np.random.random((5, 2))
def transform(X):
    r = np.sqrt(np.sum(X**2, axis=1)).reshape(-1, 1)
    fi = np.arctan2(X[:, 1], X[:, 0]).reshape(-1, 1)
    return np.concatenate((r, fi), axis=1)

print(transform(X))
## your code

[[0.54331307 1.39333656]
 [0.85163172 0.19713846]
 [0.81935428 1.47549839]
 [1.24867737 0.77997126]
 [0.87160556 1.53953606]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [53]:
X = np.random.random((10, 10))
s = np.argmax(X)
print(s//10, s%10) #mod div
## your code

1 7


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [36]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
pnt2 = np.argmin(np.sqrt(np.sum((X-y)**2, axis=1)))
print(X[pnt])
## your code

[0.22447375 0.76067931]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [51]:
## your code
@np.vectorize
def f(x):
    if x < 0:
        return x**2 + 2*x + 6
    if 0 <= x <= 2:
        return x + 6
    if x >= 2:
        return x**2 + 4*x - 4

pts = np.arange(-3,4,0.1) 
f(pts) 

array([ 9.  ,  8.61,  8.24,  7.89,  7.56,  7.25,  6.96,  6.69,  6.44,
        6.21,  6.  ,  5.81,  5.64,  5.49,  5.36,  5.25,  5.16,  5.09,
        5.04,  5.01,  5.  ,  5.01,  5.04,  5.09,  5.16,  5.25,  5.36,
        5.49,  5.64,  5.81,  6.  ,  6.1 ,  6.2 ,  6.3 ,  6.4 ,  6.5 ,
        6.6 ,  6.7 ,  6.8 ,  6.9 ,  7.  ,  7.1 ,  7.2 ,  7.3 ,  7.4 ,
        7.5 ,  7.6 ,  7.7 ,  7.8 ,  7.9 ,  8.  ,  8.81,  9.64, 10.49,
       11.36, 12.25, 13.16, 14.09, 15.04, 16.01, 17.  , 18.01, 19.04,
       20.09, 21.16, 22.25, 23.36, 24.49, 25.64, 26.81])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [37]:
X = np.random.random((10, 10))
X - X.mean(axis=1)
## your code

array([[ 0.31309948,  0.02477032,  0.58944749,  0.28913762,  0.19985475,
        -0.11229132, -0.24913122, -0.10277723,  0.40109111, -0.26500657],
       [ 0.25490286, -0.32227034,  0.27566975, -0.15101021, -0.0159015 ,
         0.35702568,  0.31697728,  0.17162613, -0.41408241, -0.04774967],
       [ 0.18535117,  0.09952694,  0.02754376, -0.36364246, -0.25154636,
        -0.22500162, -0.39004283, -0.34351609, -0.23470655,  0.06466322],
       [ 0.00693548, -0.30900049,  0.48981869, -0.22400503, -0.49508189,
         0.58673403,  0.4121853 ,  0.23065987, -0.30180942,  0.50705203],
       [-0.38441047,  0.02071147,  0.00066826,  0.07235382, -0.28881984,
        -0.27761912,  0.00968631,  0.24424455,  0.52227924,  0.50545068],
       [-0.25158176,  0.3240385 , -0.08653605, -0.41486836, -0.29436783,
        -0.03070261, -0.03965181,  0.03714701,  0.06475521, -0.35186603],
       [-0.17537682,  0.10644373, -0.25098199, -0.25065741, -0.51579784,
         0.1920735 ,  0.31889161,  0.40198359

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [39]:
X = np.random.normal(loc=5, scale=2., size=1000)
print(X.mean(),X.var())

4.895283595147213 4.0467526675783985


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [56]:
## your code
X = np.arange(0,5,1) 
X = np.append(X, [np.roll(X, -1), np.roll(X, -2), np.roll(X, -3), np.roll(X, -4)]).reshape(5,5)
print(X)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [60]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[4, 4, 4, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [62]:
## your code
def sample_new(x, c):
    assert len(x) > 0
    s = np.cumsum(x) 
    summ = np.sum(x) 
    res = summ * np.random.random(c)
    argmax = (res.reshape(-1, 1) < s).argmax(axis=1)   
    return argmax.tolist()
    
sample_new([50, 3, 1, 7, 20], 5)

[0, 4, 0, 4, 0]